### ISSUE TITLE
Accessing SubmissionOnCVFold by backreference is causing memory leak

### ISSUE THREAD

**Issue by rth** [paris-saclay-cds/ramp-board#190] opened 2019-03-11 21:53 UTC
The memory usage by the frontend with some trafic appears to be quite large,

![memory_usage](https://user-images.githubusercontent.com/630936/54160229-49a27700-444f-11e9-8612-5050e0296f90.png)
 
This is using gunicorn with 8 workers, and a large worker timeout (of 1 hours) due to #187 . Reducing the timeout value to a more reasonable amount will likely fix this, but still the amount of memory used is quite surprising. 

After restarting the frontend I see the memory usage go down from 23GB to 7 GB, meaning that 16GB RAM were used by the frontend. Even allowing for multiple processes this value is huge (given that the frontend does not run submissions), and might be worth investigating.

**Comment by glemaitre** [comment] 2019-03-12 16:46
We should need to profile that to find the cause.
Let's remove the user interaction, they are pretty useless in practice.

**Comment by jorisvandenbossche** [comment] 2019-03-12 16:49
>  Let's remove the user interaction, they are pretty useless in practice.

Yes, or at least have an option to disable/enable them

**Comment by kegl** [comment] 2019-03-12 16:51
The apache server at ramp.studio also leaks so this may be an old issue. Pls keep user interactions optionally, with default being switched off.

**Comment by glemaitre** [comment] 2019-03-13 23:29
The memory leak could be leak to the debug mode of SQLAlchemy:
https://github.com/pallets/flask-sqlalchemy/issues/181

@rth I see that on your server the option is still on. Could you try to turn this off and check again.

**Comment by rth** [comment] 2019-03-14 13:48
Thanks for investigating! Honestly, I am fairly skeptical about SqlAlchemy leaking memory with default settings. If that was indeed the case that issue would see much more activity. Also we are talking about GB of memory, that is a lot of debug information for a website with 20 visitors.

I'll try disabling the debug parameter at some point, but another avenue to explore is,

> If your application is calling create_engine() many times, like per test, or per request, or something like that, this will cause ORM related caches to grow to their max size.

Are we sure we are not re-creating a new engine for each request? Reusing the DB connection might help https://stackoverflow.com/a/17998485/1791279

**Comment by glemaitre** [comment] 2019-03-14 13:59
We are only creating a single engine. Then, I don't know how it is managed with multiple processes.

**Comment by rth** [comment] 2019-03-14 14:04
Hmm, yes you are right, it only happens when the app is started.

I imagine each process has its own engine which should be fine.

**Comment by glemaitre** [comment] 2019-03-14 14:07
But this is true that we don't implement any teardown anywhere.
I am not really sure where it should go and it would work.

**Comment by kegl** [comment] 2019-03-14 15:02
I'm wondering if this is related to the fact that we don't log out people automatically. Keeping them logged in certainly requires a process running, doesn't it?

**Comment by glemaitre** [comment] 2019-03-15 22:22
So by playing with the production server of @rth (we do safe stuff indeed), I could identify that the adding submission to the db is not the issue but rather the update of the leaderboard at the end of this manipulation.

In short, the process is very slow which is explaining why the server is not responsive when adding a submission (when so synchronization error). We should remove this part of the code.
Since the dispatcher will be in charge of updating the leaderboard once the submission trained, I don't think that it will be actually a problem.

**Comment by glemaitre** [comment] 2019-03-15 22:23
And the excessive memory consumption should be due to some of the processing there.
Since it happens in the process of gunicorn then we are keeping the objects alive.

**Comment by glemaitre** [comment] 2019-03-15 22:30
I can confirm that this is the actual issue. We should then only update the pending leaderboard.
Also we should check why updating a leaderboard is requesting 16 GB of RAM (Pandas copies?)

**Comment by glemaitre** [comment] 2019-03-15 22:35
Thanks @rth for the server. I could not reproduce locally since I add only a couple of submissions and we needed much more to detect the issue.

@jorisvandenbossche Are we aware that computing the score in solar wind is resource consuming.

**Comment by rth** [comment] 2019-03-17 12:24
Great! Thanks for getting to the bottom of it @glemaitre !

**Comment by kegl** [comment] 2019-03-17 17:35
Thanks a lot @glemaitre, this has been a long standing issue.

**Comment by jorisvandenbossche** [comment] 2019-03-18 10:17
>  Also we should check why updating a leaderboard is requesting 16 GB of RAM (Pandas copies?)

That doesn't seem very likely, since the leaderboard itself is not a big table?

Any idea where the actual big memory usage is coming from here? (are submissons blended on this step?)

And why will this not be a problem in the dispatcher loop?

(just trying to understand the issue and the fix)

**Comment by glemaitre** [comment] 2019-03-18 11:12
Let say that the fix does not may blow-up the frontend. However, the dispatcher will suffer from this issue.

Another possibility (but I am not knowledgeable in database), could the submissions be cached when calling the database. It might explain why when increasing the number of submissions we get a larger memory usage.

**Comment by glemaitre** [comment] 2019-03-18 19:20
So the issue is coming from the `get_scores` queries. I need to check why is it not releasing memory.

**Comment by glemaitre** [comment] 2019-03-18 19:39
https://github.com/paris-saclay-cds/ramp-board/blob/edbeb746386d0859fa7dadf69e8d9a047e24f0ce/ramp-database/ramp_database/tools/submission.py#L433-L443

So the dataframe is only 920 bytes. The only thing which is leaking here is by accessing `on_cv_folds` and `scores` which should have some backreferences which are not relased.
I don't see anything else.

**Comment by glemaitre** [comment] 2019-03-18 19:47
And basically the issue is that we are loading some numpy array everytime (probably the prediction) everytime that we are accessing to the `cv_fold` and this is not release. Not sure that I have a solution there.

**Comment by glemaitre** [comment] 2019-03-18 22:04
So

```python
for cv_fold in submission.on_cv_folds: 
    ...
```

will trigger to unpickle the prediction and numpy array.
Anybody has an idea on how to dereference once we don't use `cv_fold`.
I tried to `del` the object  and `gc.collect()`, use indexing instead of iterating on the list but I was unsuccessful.

I would appreciate any informed opinion here.

**Comment by glemaitre** [comment] 2019-03-18 22:29
So the solution is make a query instead of using the backreferencing from SQLAlchemy.

**Comment by kegl** [comment] 2019-03-18 22:34
Wow, thanks a lot for finding this. The other solution may be to take the predictions out of the DB so they are only loaded when needed.

**Comment by glemaitre** [comment] 2019-03-20 11:10
We actually need to address all the access by backreference.

**Comment by glemaitre** [comment] 2019-03-20 11:11
Should be linked to:

* https://github.com/paris-saclay-cds/ramp-backend/issues/7
* https://github.com/zzzeek/sqlalchemy/pull/441
* https://github.com/sqlalchemy/sqlalchemy/issues/4549

**Closed** 2019-03-20 21:43 UTC
Labels: bug, frontend
